[build]
/               /
/messenger      /messenger
/categories     /categories
/recommendation /recommendation
/privacy        /privacy
/tos            /tos

base = "/"
publish = "/frontend/build"
command = "yarn build"

